# validate tmapp
# this code takes a tmapp simulation in switzerland finds all IMIS stationds in domain and validates over simulation time.
require(raster)
require(ini)

# args
wd="/home/joel/sim/ch_basin/"
simPath="/home/joel/sim/ch_basin/sim/g3"
imisShp=shapefile("/home/joel/data/imis/IMIS2019_ll.shp")
imisDir = "/home/joel/data/imis/fromDPS"# directory containing smet fies generated by meteoio with standard processing

# derived paths
ele = raster(paste0(simPath,'/predictors/ele.tif'))
lf=raster(paste0(simPath,'/landform.tif'))
config = read.ini(paste0(wd,"/config.ini"))
startDate=config$main$startDate
endDate=config$main$endDate

# find IMIS stations in Domain
pointsInDomain =extract(ele,imisShp)
pointsInDomain_index = which(!is.na(pointsInDomain))
imisInDomainShp = imisShp[pointsInDomain_index,]
plot(ele)
plot(imisInDOmainShp, add=T)

imisInDomainID = imisInDomainShp$IMIS_ST
tsubIDs = extract(lf, imisInDomainShp)
df = data.frame(imisInDomainID, tsubIDs)

# find IMIS data that exists in imisDir
imisfilepaths = paste0(imisDir,"/",imisInDomainID, ".smet")
foundSmets = imisfilepaths[which(file.exists(imisfilepaths))]
print(paste0("I found the following validation IMIS smet files: ", foundSmets))
par(mfrow=c(4,4))
par(mai=c(0.2,0.2,0.2,0.2))
for ( smet in foundSmets ){

# get imis ID eg "KES2"
imisID = unlist(strsplit(unlist(strsplit(smet,'/'))[length(unlist(strsplit(smet,"/")))], '.smet'))
tsubID = df$tsubIDs[which(df$imisInDomainID==imisID)]

# parse smet file
print(paste0("Now parsing ", smet))
header = readLines(smet, n=200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip =which(header=="[DATA]")
imis =read.csv(smet, skip=skip, header=F, sep='')
names(imis)<-fields

if(length(imis$HS)==0){print(paste0("No HS found in ",imisID)); next}

# Aggregate to daily

daily = substr(imis$timestamp, 1, 10)
HS = aggregate(imis$HS,by=list(daily), FUN="mean", na.rm=T)
HS$x[HS$x<0] <-NA



# crop to dates
start = which(HS$Group.1==startDate)
end = which(HS$Group.1==endDate)
HS<- HS$x # height snow in m
HS.imis=HS[start:end]

# parse GEOTOP results
tsubIDformat = formatC(tsubID,width=5,flag='0')
gt=read.csv(paste0(simPath,"/c",tsubIDformat,"/out/surface.txt"))

# crop to dates (convert geotop to iso)
date=as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
gt$date<- date
start=which(gt$date==startDate) 
end=which(gt$date==endDate) 
geotop.dates = gt$date[start:end]

HS.gt = gt$snow_depth.mm.[start:end]/1000

plot(HS.gt, type='l', col='red', sub=imisID)
lines(HS.imis)
}



