# validate tmapp
# this code validates point toposcale sim and validates against equivalent IMIS station
require(raster)
require(ini)
require(hydroGOF)

# args
wd="/home/joel/sim/imis_1h/"
imisShp=shapefile("/home/joel/data/imis/IMIS2019_ll.shp")
imisDir = "/home/joel/data/imis/fromDPS"# directory containing smet fies generated by meteoio with standard processing

# derived paths
lpfile= paste0(wd, "/listpoints.txt")
config = read.ini(paste0(wd,"/config.ini"))
startDate=config$main$startDate
endDate=config$main$endDate

# find IMIS stations in Domain
lp=read.csv(lpfile)
stations = lp$name
index=1:length(stations)
df = data.frame(index, stations)

# find IMIS data that exists in imisDir
imisfilepaths = paste0(imisDir,"/",stations, ".smet")
foundSmets = imisfilepaths[which(file.exists(imisfilepaths))]
print(paste0("I found the following validation IMIS smet files: ", foundSmets))
par(mfrow=c(4,4),oma = c(0, 0, 2, 0))
rvec=c()
for ( smet in foundSmets ){

# get imis ID eg "KES2"
imisID = unlist(strsplit(unlist(strsplit(smet,'/'))[length(unlist(strsplit(smet,"/")))], '.smet'))
id = which(df$stations==imisID)

# parse smet file
print(paste0("Now parsing ", smet))
header = readLines(smet, n=200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip =which(header=="[DATA]")
imis =read.csv(smet, skip=skip, header=F, sep='')
names(imis)<-fields

if(length(imis$HS)==0){print(paste0("No HS found in ",imisID)); next}

# Aggregate to daily

daily = substr(imis$timestamp, 1, 10)
imis_daily1 = aggregate(imis,by=list(daily), FUN="mean", na.rm=T)

# crop to dates
start = which(imis_daily1$Group.1==startDate)
end = which(imis_daily1$Group.1==endDate)
imis_daily= imis_daily1[start:end,]
names(imis_daily)[1]<-"Date"		
## parse GEOTOP results
#tsubIDformat = formatC(tsubID,width=5,flag='0')
#gt=read.csv(paste0(simPath,"/c",tsubIDformat,"/out/surface.txt"))

## crop to dates (convert geotop to iso)
#date=as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
#gt$date<- date
#start=which(gt$date==startDate) 
#end=which(gt$date==endDate) 
#geotop.dates = gt$date[start:end]

#HS.gt = gt$snow_depth.mm.[start:end]/1000

#plot(HS.gt, type='l', col='red', sub=imisID)
#lines(HS.imis)

# parse snowpack smets
simDat = read.csv(paste0(wd, '/out/meteoc',id,'.csv' ))
daily = substr(simDat$datetime, 1, 10)
simdat_daily = aggregate(simDat,by=list(daily), FUN="mean", na.rm=T)

if (length(imis_daily$TA) !=length(simdat_daily$TA) ){

shorterOne =  c(length(imis_daily$TA),length(simdat_daily$TA))[which.min( c(length(imis_daily$TA),length(simdat_daily$TA) ) )]
simdat_daily = simdat_daily[1:shorterOne,]
imis_daily = imis_daily[1:shorterOne,]
}

# plot results
myrmse=round(rmse(imis_daily$TA, simdat_daily$TA),2)
plot(imis_daily$TA, simdat_daily$TA, main=paste(imisID, "rmse=",myrmse), xlab="",ylab="")
abline(0,1)

rvec=c(rvec,myrmse)
}

print(mean(rvec))


