require(raster)
require(ini)
require(hydroGOF)

            model = "GEOTOP" # snowpack code needs fixining obsSimNSE.R in src/snowpack
            var = "HS"

            # args
            wd = "/home/joel/sim/tmapp_val/points/sim2"
            imisShp = shapefile("/home/joel/sim/tmapp_val/points/points.shp")
            imisDir = "/home/joel/data/imis/fromDPS"# directory containing smet fies generated by meteoio with standard processing

            # derived paths
            lpfile = paste0(wd, "/listpoints.txt")
            config = read.ini(paste0(wd, "/config.ini"))
            startDate = config$main$startDate
            endDate = config$main$endDate

            # find IMIS stations in Domain
            lp = read.csv(lpfile)
            stations = lp$name
            index = 1 : length(stations)
            df = data.frame(index, stations)

            # find IMIS data that exists in imisDir
            imisfilepaths = paste0(imisDir, "/", stations, ".smet")
            foundSmets = imisfilepaths[which(file.exists(imisfilepaths))]
            print(paste0("I found the following validation IMIS smet files: ", foundSmets))
            par(mfrow = c(4, 4), oma = c(0, 0, 2, 0))
            rvec = c()
            for (smet in foundSmets) {

                # get imis ID eg "KES2"
                imisID = unlist(strsplit(unlist(strsplit(smet, '/'))[length(unlist(strsplit(smet, "/")))], '.smet'))
                id = which(df$stations == imisID)

                # parse smet file
                print(paste0("Now parsing ", smet))
                header = readLines(smet, n = 200)
                fieldsLine = grep(pattern = "fields", x = header)
                fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields'
                skip = which(header == "[DATA]")
                imis = read.csv(smet, skip = skip, header = F, sep = '')
                names(imis) <- fields

                if (length(imis$HS) == 0) {print(paste0("No HS found in ", imisID)); next}

                # Aggregate to daily
                daily = substr(imis$timestamp, 1, 10)
                imis_daily1 = aggregate(imis, by = list(daily), FUN = "mean", na.rm = T)

                # crop to dates
                start = which(imis_daily1$Group.1 == startDate)
                end = which(imis_daily1$Group.1 == endDate)
                imis_daily = imis_daily1[start : (end - 1),]
                names(imis_daily)[1] <- "Date"

                if (model == "GEOTOP") {
                    tsubIDformat = formatC(id, width = 5, flag = '0')
                    gt = read.csv(paste0(wd, "/c", tsubIDformat, "/out/surface.txt"))

                    date = as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
                    gt$date <- date
                    start = which(gt$date == startDate)
                    end = which(gt$date == endDate)
                    gt <- gt[(start + 1) : end,]
                    geotop.dates = gt$date





                    if (var == 'SW') {
                        gt = read.csv(paste0(wd, "/c", tsubIDformat, "/meteo0001.txt"))

                        # Aggregate to daily
                        day = substr(gt$Date, 1, 2)
                        mo = substr(gt$Date, 4, 5)
                        yr = substr(gt$Date, 7, 10)
                        date_day = paste0(yr, mo, day)
                        gt = aggregate(gt, by = list(date_day), FUN = "mean", na.rm = T)
                    }



                    if (var == 'TA')
                    {            ## parse GEOTOP results
                        # tsubIDformat = formatC(id, width = 5, flag = '0')
                        # gt = read.csv(paste0(wd, "/c", tsubIDformat, "/out/surface.txt"))
                        #
                        # ## crop to dates (convert geotop to iso)
                        # date = as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
                        # gt$date <- date
                        # start = which(gt$date == startDate)
                        # end = which(gt$date == endDate)
                        # geotop.dates = gt$date #[(start+1):end]

                        HS.gt = gt$Tair.C.
                        HS.gt2 = HS.gt
                        myrmse = round(rmse(HS.gt2, imis_daily$TA - 273.13), 2)
                        plot(HS.gt2, type = 'l', col = 'red', main = paste(imisID, "rmse=", myrmse))
                        lines(imis_daily$TA - 273.13)
                    }

                    if (var == 'HS')
                    {            ## parse GEOTOP results
                        # tsubIDformat = formatC(id, width = 5, flag = '0')
                        # gt = read.csv(paste0(wd, "/c", tsubIDformat, "/out/surface.txt"))

                        ## crop to dates (convert geotop to iso)
                        # date = as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
                        # gt$date <- date
                        #start = which(gt$date == startDate)
                        #end = which(gt$date == endDate)


                        HS.gt = gt$snow_depth.mm. / 1000
                        HS.gt2 = HS.gt
                        #myrmse = round(rmse(HS.gt2 , imis_daily$HS), 2)
                        mymax=max(c(max(HS.gt2,na.rm=T), max(imis_daily$HS,na.rm=T)))
                        plot(HS.gt2, type = 'l', col = 'red', main = paste(imisID, "rmse="), ylim=c(0, mymax))
                        lines(imis_daily$HS)

                        cols=rainbow(31)
                        # 12 ids good one
                        for (i in 1:31){
                            mycol=cols[i]
                            fsm = read.csv(paste0(wd,"/out/FSM/meteoc",id,".csv",i,"out.txt"), header=F,sep='')
                            fsm_hs=fsm$V7
                            lwd=1
                            if(i==15){lwd=5}
                            lines(fsm_hs/100, col=mycol,lwd=lwd)
                        }


                    }

                    if (var == 'SW')
                    {            ## parse GEOTOP results
                        # tsubIDformat = formatC(id, width = 5, flag = '0')
                        # gt = read.csv(paste0(wd, "/c", tsubIDformat, "/meteo0001.txt"))
                        #
                        # ## crop to dates (convert geotop to iso)
                        # date = as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
                        # gt$date <- date
                        # start = which(gt$date == startDate)
                        # end = which(gt$date == endDate)
                        # geotop.dates = gt$date[start : end]

                        HS.gt = gt$SW
                        HS.gt2 = HS.gt
                        if (length(imis_daily$ISWR) == 0){
                            next
                        }

                        myrmse = round(rmse(HS.gt2, imis_daily$ISWR), 2)


                        plot(HS.gt2, type = 'l', col = 'red', sub = imisID)

                        lines(imis_daily$SW)
                    }
               


#======================================================================================

smet1= paste0(wd,"/forcing/meteoc",id,"_",imisID,".smet")

if(file.exists(smet1)){
imisID = unlist(strsplit(unlist(strsplit(smet1,'/'))[length(unlist(strsplit(smet1,"/")))], '.smet'))

# parse smet file
print(paste0("Now parsing ", smet1))
header = readLines(smet1, n=200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip =which(header=="[DATA]")
s1 =read.csv(smet1, skip=skip, header=F, sep='')
names(s1)<-fields
}

                         
lines(s1$HS_mod/100, col='blue')
legend('topright', legend=c('obs', 'FSM', 'GEOTOP', 'SNOWPACK'), col=c('black','green', 'red', 'blue'), lwd=1)
#======================================================================================


        }        


                if (model == "SNOWPACK") {
                    # parse snowpack smets

                    if (file.exists(paste0(wd, '/forcing/meteoc', id, '.csv'))==FALSE){next}
                    simDat = read.csv(paste0(wd, '/forcing/meteoc', id, '.csv'))
                    daily = substr(simDat$datetime, 1, 10)
                    simdat_daily = aggregate(simDat, by = list(daily), FUN = "mean", na.rm = T)

                    if (length(imis_daily$TA) != length(simdat_daily$TA)) {

                        shorterOne = c(length(imis_daily$TA), length(simdat_daily$TA))[which.min(c(length(imis_daily$TA), length(simdat_daily$TA)))]
                        simdat_daily = simdat_daily[1 : shorterOne,]
                        imis_daily = imis_daily[1 : shorterOne,]
                    }

                    # plot results
                    myrmse = round(rmse(imis_daily$HS, simdat_daily$HS), 2)
                    plot(imis_daily$HS, simdat_daily$HS, main = paste(imisID, "rmse=", myrmse), xlab = "", ylab = "")
                    abline(0, 1)
                }
               # rvec = c(rvec, myrmse)
            

            print(paste(var, 'mean RMSE=', mean(rvec)))



}





