#Rscript tscale_validate_wfj.R "/home/joel/sim/tmapp_val/wfj_valCase/" GEOTOP

args = commandArgs(trailingOnly=TRUE)
wd=args[1]
model=args[2]

# validate tmapp
# this code validates point toposcale sim and validates against equivalent IMIS station
require(raster)
require(ini)
require(hydroGOF)
require(ncdf4)
# args
#wd = "/home/joel/sim/wfj_intercomp/"
#wd = "/home/joel/sim/tmapp_val/points/sim1"
#wd="/home/joel/sim/tmapp_val/wfj_valCase/"
#model='GEOTOP'

#imisShp = shapefile("/home/joel/data/imis/IMIS2019_ll.shp")
#imisDir = "/home/joel/data/imis/fromDPS"# directory containing smet fies generated by meteoio with standard processing

# derived paths
lpfile = paste0(wd, "/listpoints.txt")
config = read.ini(paste0(wd, "/config.ini"))
startDate = config$main$startDate
endDate = config$main$endDate

# find IMIS stations in Domain
lp = read.csv(lpfile)
stations = lp$name
index = 1 : length(stations)
df = data.frame(index, stations)



smet = "/home/joel/data/imis/WFJ_optimaldataset_v7.smet"

# get imis ID eg "KES2"
imisID = "WFJ2"
id = which(df$stations == imisID)

# parse smet file
print(paste0("Comparing tmapp data to", smet))
header = readLines(smet, n = 200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip = which(header == "[DATA]")
imis = read.csv(smet, skip = skip, header = F, sep = '')
names(imis) <- fields



# Aggregate to daily

daily = substr(imis$timestamp, 1, 10)
imis_daily1 = aggregate(imis, by = list(daily), FUN = "mean", na.rm = T)
imis_daily1$PSUM = aggregate(imis$PSUM, by = list(daily), FUN = "sum", na.rm = T)$x
# crop to dates
start = which(imis_daily1$Group.1 == startDate)
end = which(imis_daily1$Group.1 == endDate)
imis_daily = imis_daily1[start : end,]
names(imis_daily)[1] <- "Date"



if (model == 'GEOTOP') {
    ## parse GEOTOP results
    tsubIDformat = formatC(id, width = 5, flag = '0')
    gt = read.csv(paste0(wd, "/c", tsubIDformat, "/meteo0001.txt"))
    #step = as.numeric(substr(gt$Date[2],12,13)) - as.numeric(substr(gt$Date[1],12,13))  
                    # Aggregate to daily
                    day = substr(gt$Date, 1, 2)
                    mo = substr(gt$Date, 4, 5)
                    yr = substr(gt$Date, 7, 10)
                    date_day = paste0(yr, mo, day)
                    simdat_daily  = aggregate(gt, by = list(date_day), FUN = "mean", na.rm = T)

    # crop to dates (convert geotop to iso)
    # date = as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
    # gt$date <- date
    # start = which(gt$date == startDate)
    # end = which(gt$date == endDate)
    # geotop.dates = gt$date[start : end]
    #
    # HS.gt = gt$snow_depth.mm.[start : end] / 1000
    #
    # plot(HS.gt, type = 'l', col = 'red', sub = imisID)
    # lines(HS.imis)


names(simdat_daily) <- c('Date', 'Date2', 'PINT', 'VW', 'DW', 'RH', 'TA', 'ISWR', 'ILWR')

simdat_daily$TA <- simdat_daily$TA+273.15
simdat_daily$RH <- simdat_daily$RH/100

surface = read.csv(paste0(wd,"/c00001/out/surface.txt"))
simout= surface
simout$HS_mod  <- simout$snow_depth.mm./10



}

# if (model == 'FSM') {

# inDir=paste0(wd,"/out/FSM/")
# fsm = read.csv(paste0(inDir,"/meteoc1.csv",13,"out.txt"), header=F,sep='')



#     #mycol=cols[i]
#     fsm_hs=c(fsm$V6)
#     fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
    

# }

if (model == 'SNOWPACK') {
    # parse snowpack smets
    simDat = read.csv(paste0(wd, '/forcing/meteoc', id, '.csv'))
    daily = substr(simDat$datetime, 1, 10)
    simdat_daily = aggregate(simDat, by = list(daily), FUN = "mean", na.rm = T)


smet =    "/home/joel/sim/tmapp_val/wfj_valCase/forcing/meteoc1_WFJ2.smet"
header = readLines(smet, n = 200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip = which(header == "[DATA]")
simout = read.csv(smet, skip = skip, header = F, sep = '')
names(simout) <- fields



}

if (model != 'FSM') {

    if (length(imis_daily$TA) != length(simdat_daily$TA)) {

        shorterOne = c(length(imis_daily$TA), length(simdat_daily$TA))[which.min(c(length(imis_daily$TA), length(simdat_daily$TA)))]
        simdat_daily = simdat_daily[1 : shorterOne,]
        imis_daily = imis_daily[1 : shorterOne,]
    }

    # clean
    imis_daily$TA[imis_daily$TA < 250] <- NA
    imis_daily$RH[imis_daily$RH < - 1] <- NA
    imis_daily$PSUM[imis_daily$PSUM < 0] <- NA
 imis_daily$PSUM[imis_daily$HS< 0] <- NA


pdf(paste0(wd,"/valplot_",model,".pdf"), width=5, height=10)
par(mfrow = c(4, 2), oma = c(0, 0, 2, 0))
# plot results
myrmse = round(rmse(imis_daily$TA, simdat_daily$TA), 2)
plot(imis_daily$TA, simdat_daily$TA, main = paste(imisID, "TA rmse=", myrmse), xlab = "WFJ OBS", ylab = "MODEL")
abline(0, 1)

myrmse = round(rmse(imis_daily$RH, simdat_daily$RH), 2)
plot(imis_daily$RH, simdat_daily$RH, main = paste(imisID, "RH rmse=", myrmse), xlab = "WFJ OBS", ylab = "MODEL")
abline(0, 1)

myrmse = round(rmse(imis_daily$VW, simdat_daily$VW), 2)
plot(imis_daily$VW, simdat_daily$VW, main = paste(imisID, "VW rmse=", myrmse), xlab = "WFJ OBS", ylab = "MODEL")
abline(0, 1)

myrmse = round(rmse(imis_daily$ILWR, simdat_daily$ILWR), 2)
plot(imis_daily$ILWR, simdat_daily$ILWR, main = paste(imisID, "ILWR rmse=", myrmse), xlab = "WFJ OBS", ylab = "MODEL") 
abline(0, 1)

myrmse = round(rmse(imis_daily$ISWR, simdat_daily$ISWR), 2)
plot(imis_daily$ISWR, simdat_daily$ISWR, main = paste(imisID, "ISWR rmse=", myrmse), xlab = "WFJ OBS", ylab = "MODEL")
abline(0, 1)

myrmse = round(rmse(imis_daily$PSUM, simdat_daily$PINT*24), 2)
#plot(cumsum(imis_daily$PSUM)  , main = paste(imisID, "PSUM rmse=", myrmse), xlab = "time", ylab = "cumsum mm", type = 'l')
#lines(cumsum( simdat_daily$PINT*24), col = 'red')
sum(simdat_daily$PINT*24, na.rm = T) 
sum(imis_daily$PSUM, na.rm = T)



plot((imis_daily$HS) , main = paste(imisID, "HS rmse="), xlab = "time", ylab = "cm", type = 'l')
lines( (simout$HS_mod), col = 'red')
legend('bottomright', c('WFJ OBS', 'MODEL'), col=c('black', 'red'), lty=1) 

dev.off()

}
if (model == 'FSM') {

pdf(paste0(wd,"/valplot_",model,".pdf"), width=10, height=10)
par(mfrow = c(3, 2), oma = c(0, 0, 2, 0))

plot((imis_daily$HS) , main = paste(imisID, "HS rmse="), xlab = "time", ylab = "cm", type = 'l')
for (i in 30){
i = formatC(i, width=2, flag="0")    
inDir=paste0(wd,"/out/FSM/")
fsm = read.csv(paste0(wd,"/out/FSM/fsm001.txt_",i,".txt"), header=F,sep='')

# HS
fsm_hs=c(fsm$V6)
fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
lines( (fsm_hs*100), col = 'red')
legend('bottomright', c('WFJ OBS', 'MODEL'), col=c('black', 'red'), lty=1) 
}


# SWE
fsm_hs=c(fsm$V7)
fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
    
    #     if (length(imis_daily$Date) != length(fsm_dates)) {

    #     shorterOne = c(length(imis_daily$TA), length(fsm_dates))[which.min(c(length(imis_daily$TA), length(fsm_dates)))]
    #     fsm_hs= fsm_hs[1 : shorterOne]
    #     fsm_dates= fsm_dates[1 : shorterOne]
    #     imis_daily = imis_daily[1 : shorterOne,]
    # }

#plot(imis_daily$Date,imis_daily$SWE_M , main = paste(imisID, "SWE"), xlab = "time", ylab = "cm", type = 'l',ylim=c(0,1000 ))
#lines( fsm_dates, fsm_hs, col = 'red')


# Soil T
fsm_tsg=c(fsm$V9)
fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
    
plot((imis_daily$TSG) , main = paste(imisID, "TSG rmse="), xlab = "time", ylab = "cm", type = 'l',ylim=c(253.15,293.15 ))
lines( (fsm_tsg+273.15), col = 'red')

# surface T
fsm_tss=c(fsm$V8)
fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
    
plot((imis_daily$TSS) , main = paste(imisID, "TSS rmse="), xlab = "time", ylab = "k", type = 'l', ylim=c(253.15,293.15 ))
lines( (fsm_tss+273.15), col = 'red')

legend('bottomright', c('WFJ OBS', 'MODEL'), col=c('black', 'red'), lty=1) 

# surface T
fsm_lys=c(fsm$V5)
fsm_dates=as.Date(paste(fsm$V1,fsm$V2,fsm$V3 ,sep='-'))
    
plot((imis_daily$LYSI) , main = paste(imisID, "TSS rmse="), xlab = "time", ylab = "k", type = 'l', ylim=c(253.15,293.15 ))
lines( (fsm_lys), col = 'red')

legend('bottomright', c('WFJ OBS', 'MODEL'), col=c('black', 'red'), lty=1) 

dev.off()
}
#plot(imis_daily$ISWR, type='l')
#lines(simdat_daily$ISWR, col='red')

# careful with this valid only for certain sim directories grid level is best!
#nc=nc_open("/home/joel/sim/imis_1h/forcing/SURF.nc")
#sw=ncvar_get(nc, "ssrd")
#sw=sw[12,3,]
#time = ncvar_get( nc,'time')
#z <- time*60*60 #make seconds
#origin = unlist(strsplit(nc$dim$time$units, " "))[[3]]
#dates<-ISOdatetime(origin,0,0,0,0,0,tz='UTC') + z #dates sequence
#s =which(substr(dates,1,10)==startDate)[1]
#e = which(substr(dates,1,10)==endDate)[length(which(substr(dates,1,10)==endDate))]
#d=substr(dates,1,10)
#sw_day=aggregate(sw, list(d), "mean")
#s =which(sw_day$Group.1==startDate)
#e = which(sw_day$Group.1==endDate)
#sw_day=sw_day$x[s:e]
# plot(sw_day/3600, imis_daily$ISWR[1:732])
# abline(0,1)

#plot(imis_daily$ISWR[1:732], type='l')
#lines(sw_day/3600 )
#lines(simdat_daily$ISWR, col='red')
