# validate tmapp
# this code validates point toposcale sim and validates against equivalent IMIS station
require(raster)
require(ini)
require(hydroGOF)
require(ncdf4)
# args
wd="/home/joel/sim/wfj_intercomp/"
imisShp=shapefile("/home/joel/data/imis/IMIS2019_ll.shp")
imisDir = "/home/joel/data/imis/fromDPS"# directory containing smet fies generated by meteoio with standard processing

# derived paths
lpfile= paste0(wd, "/listpoints.txt")
config = read.ini(paste0(wd,"/config.ini"))
startDate=config$main$startDate
endDate=config$main$endDate

# find IMIS stations in Domain
lp=read.csv(lpfile)
stations = lp$name
index=1:length(stations)
df = data.frame(index, stations)

# find IMIS data that exists in imisDir
imisfilepaths = paste0(imisDir,"/",stations, ".smet")
foundSmets = imisfilepaths[which(file.exists(imisfilepaths))]
print(paste0("I found the following validation IMIS smet files: ", foundSmets))
par(mfrow=c(3,2),oma = c(0, 0, 2, 0))


smet = "/home/joel/data/imis/WFJ_optimaldataset_v7.smet"

# get imis ID eg "KES2"
imisID = "WFJ2"
id = which(df$stations==imisID)

# parse smet file
print(paste0("Now parsing ", smet))
header = readLines(smet, n=200)
fieldsLine = grep(pattern = "fields", x = header)
fields = unlist(strsplit(unlist(strsplit(header[fieldsLine], "= "))[2], " ")) # space after equals vey important or else a empty " " element is added to 'fields' 
skip =which(header=="[DATA]")
imis =read.csv(smet, skip=skip, header=F, sep='')
names(imis)<-fields



# Aggregate to daily

daily = substr(imis$timestamp, 1, 10)
imis_daily1 = aggregate(imis,by=list(daily), FUN="mean", na.rm=T)

# crop to dates
start = which(imis_daily1$Group.1==startDate)
end = which(imis_daily1$Group.1==endDate)
imis_daily= imis_daily1[start:end,]
names(imis_daily)[1]<-"Date"		
## parse GEOTOP results
#tsubIDformat = formatC(tsubID,width=5,flag='0')
#gt=read.csv(paste0(simPath,"/c",tsubIDformat,"/out/surface.txt"))

## crop to dates (convert geotop to iso)
#date=as.Date(gt$Date12.DDMMYYYYhhmm., format = "%d/%m/%Y")
#gt$date<- date
#start=which(gt$date==startDate) 
#end=which(gt$date==endDate) 
#geotop.dates = gt$date[start:end]

#HS.gt = gt$snow_depth.mm.[start:end]/1000

#plot(HS.gt, type='l', col='red', sub=imisID)
#lines(HS.imis)

# parse snowpack smets
simDat = read.csv(paste0(wd, '/out/meteoc',id,'.csv' ))
daily = substr(simDat$datetime, 1, 10)
simdat_daily = aggregate(simDat,by=list(daily), FUN="mean", na.rm=T)

if (length(imis_daily$TA) !=length(simdat_daily$TA) ){

shorterOne =  c(length(imis_daily$TA),length(simdat_daily$TA))[which.min( c(length(imis_daily$TA),length(simdat_daily$TA) ) )]
simdat_daily = simdat_daily[1:shorterOne,]
imis_daily = imis_daily[1:shorterOne,]
}

# clean
imis_daily$TA[imis_daily$TA < 250] <- NA
imis_daily$RH[imis_daily$RH < -1] <- NA
imis_daily$PSUM[imis_daily$PSUM < 0] <- NA

# plot results
myrmse=round(rmse(imis_daily$TA, simdat_daily$TA),2)
plot(imis_daily$TA, simdat_daily$TA, main=paste(imisID, "TA rmse=",myrmse), xlab="",ylab="")
abline(0,1)

myrmse=round(rmse(imis_daily$RH, simdat_daily$RH),2)
plot(imis_daily$RH, simdat_daily$RH, main=paste(imisID, "RH rmse=",myrmse), xlab="",ylab="")
abline(0,1)

myrmse=round(rmse(imis_daily$VW, simdat_daily$VW),2)
plot(imis_daily$VW, simdat_daily$VW, main=paste(imisID, "VW rmse=",myrmse), xlab="",ylab="")
abline(0,1)

myrmse=round(rmse(imis_daily$ILWR, simdat_daily$ILWR),2)
plot(imis_daily$ILWR, simdat_daily$ILWR, main=paste(imisID, "ILWR rmse=",myrmse), xlab="",ylab="")
abline(0,1)

myrmse=round(rmse(imis_daily$ISWR, simdat_daily$ISWR),2)
plot(imis_daily$ISWR, simdat_daily$ISWR, main=paste(imisID, "ISWR rmse=",myrmse), xlab="",ylab="")
abline(0,1)

myrmse=round(rmse(imis_daily$PSUM, simdat_daily$PSUM),2)
plot(cumsum(simdat_daily$PSUM),  main=paste(imisID, "PSUM rmse=",myrmse), xlab="",ylab="", type='l')
lines(cumsum(imis_daily$PSUM*24), col='red')
sum(simdat_daily$PSUM, na.rm=T)*24/2

abline(0,1)

#plot(imis_daily$ISWR, type='l')
 #lines(simdat_daily$ISWR, col='red')

# careful with this valid only for certain sim directories grid level is best!
#nc=nc_open("/home/joel/sim/imis_1h/forcing/SURF.nc")
#sw=ncvar_get(nc, "ssrd")
#sw=sw[12,3,]
#time = ncvar_get( nc,'time')
#z <- time*60*60 #make seconds
#origin = unlist(strsplit(nc$dim$time$units, " "))[[3]]
#dates<-ISOdatetime(origin,0,0,0,0,0,tz='UTC') + z #dates sequence
#s =which(substr(dates,1,10)==startDate)[1]
#e = which(substr(dates,1,10)==endDate)[length(which(substr(dates,1,10)==endDate))]
#d=substr(dates,1,10)
#sw_day=aggregate(sw, list(d), "mean")
#s =which(sw_day$Group.1==startDate)
#e = which(sw_day$Group.1==endDate)
#sw_day=sw_day$x[s:e]
# plot(sw_day/3600, imis_daily$ISWR[1:732])
# abline(0,1)

#plot(imis_daily$ISWR[1:732], type='l')
#lines(sw_day/3600 )
#lines(simdat_daily$ISWR, col='red')
